### ISSUE TITLE
Sugestão - redes sociais

### ISSUE THREAD

**Issue by Lucasgcode** [satodu/marriage-101#2]
Prezados devs, tudo bem?

Quero poder compartilhar a tabela no Instagram, é possível? É demorado?

**Comment by satodu** [comment]
## Issue Resolved

This issue has been resolved with the merge of [PR #3](https://github.com/satodu/marriage-101/pull/3).

### Summary of the Fix

The following enhancements were implemented:

1. **Share Button Functionality**:
    - The share button now only appears once the results are fully calculated, both on desktop and mobile.
    - On mobile, the share button is a floating button positioned at the bottom-right corner of the screen with a pulsing animation to draw user attention.

2. **Mobile Display Improvements**:
    - Adjusted the display of results on mobile devices to ensure the entire result (e.g., "husband is wrong") appears on the same line.
    - Removed unnecessary line breaks to improve readability and presentation on smaller screens.

### Changes Made

- **CSS Adjustments**: Added media queries to handle the display and positioning of the share button for both desktop and mobile views, ensured the share button has a pulsing animation on mobile, used CSS properties to prevent unwanted line breaks in the result cells on mobile devices, and removed pseudo-elements in mobile view to avoid redundant labels.
- **JavaScript Enhancements**: Modified the script to ensure the share button is hidden initially and only displayed once all results are calculated, and adjusted the text insertion logic to include both the name and result status on the same line, ensuring better readability on mobile devices.

For detailed changes, please refer to [PR #3](https://github.com/satodu/marriage-101/pull/3).
